import os

MAIN_FOLDER_NAME = "EE2_music_changer"
RESET_MUSIC_FOLDER_NAME = "default_music"
SAVE_DIR = os.path.join(MAIN_FOLDER_NAME, RESET_MUSIC_FOLDER_NAME)
MUSIC_FOLDER_NAME = "music"
MUSIC_CUSTOM_FOLDER_NAME = "custom_music_ee2"
DEFAULT_CUSTOM_DIR = "Documents"
AMBIENT_FOLDER_NAME = "Ambient"
EXE_FILE_NANE = "EE2.exe"
AVAILABLE_MUSIC_EXTENSION = "mp3"
OS_LINUX = "Linux"
OS_WINDOWS = "Windows"
GAME_MUSIC_NUMBER = 81

